using System.Text;

namespace CommandRefGen;

/// <summary>
/// Renders the whole reference document. Every line of the output file comes from here:
/// the do-not-edit banner, the preamble, the Contents list, each category section and the
/// RuntimeOnly section. Nothing in the output is hand-maintained.
/// </summary>
internal static class MarkdownWriter
{
    public static string Render(IReadOnlyList<CommandInfo> commands, string version, Annotations annotations)
    {
        var listed = commands.Where(c => !c.RuntimeOnly).ToList();
        var runtimeOnly = commands.Where(c => c.RuntimeOnly)
            .OrderBy(c => c.Name, StringComparer.Ordinal)
            .ToList();

        var sections = listed
            .GroupBy(c => Categories.TitleFor(c.CategoryDir))
            .OrderBy(g => Categories.SortKey(g.Key))
            .ToList();

        var sb = new StringBuilder();

        Banner(sb);
        Preamble(sb, version, commands.Count);
        Contents(sb, sections.Select(s => s.Key), runtimeOnly.Count > 0);

        foreach (var section in sections)
        {
            sb.Append("## ").Append(section.Key).Append("\n\n");
            foreach (var command in section.OrderBy(c => c.Name, StringComparer.Ordinal))
                Entry(sb, command, annotations);
        }

        if (runtimeOnly.Count > 0)
        {
            RuntimeOnlyPreamble(sb, version, runtimeOnly);
            foreach (var command in runtimeOnly)
                Entry(sb, command, annotations);
        }

        return sb.ToString().TrimEnd() + "\n";
    }

    private static void Banner(StringBuilder sb) => sb.Append("""
        <!--
        GENERATED FILE — do not hand-edit any part of it, including the preamble and the
        Contents list. Regenerate from the com.unity.pipeline package sources with:
            dotnet run --project tools/CommandRefGen -- --version latest
        No Unity Editor and no `unity --json command` dump is involved. Field notes that are
        not derivable from the package source (observed behaviour, links to other skill files)
        live in tools/CommandRefGen/annotations.json — add them there, not here.
        -->

        """).Append('\n');

    private static void Preamble(StringBuilder sb, string version, int count)
    {
        sb.Append("# Editor command reference\n\n");

        sb.Append("Generated by `tools/CommandRefGen` from the `com.unity.pipeline` package source, version `")
          .Append(version)
          .Append("` — ").Append(count)
          .Append(" commands, read from the `[CliCommand]`/`[CliArg]` attributes of the package's C# sources ")
          .Append("rather than from a live editor. The file therefore covers every command the package ")
          .Append("declares, on every Unity version it supports.\n\n");

        sb.Append("**This file is more complete than `unity command`.** The live listing is dynamic ")
          .Append("(package version, project code, optional packages, project-defined `[CliCommand]` methods), ")
          .Append("and it filters out commands whose attribute sets `RuntimeOnly = true` — those are designed ")
          .Append("for Unity **Player** connections (`unity command --runtime <player>`) — yet the editor ")
          .Append("server still executes them when called by name, in edit mode and play mode alike. The CLI ")
          .Append("never reveals their schemas; the [")
          .Append(Categories.RuntimeOnlyTitle.Split(" (")[0])
          .Append("](#").Append(Categories.Anchor(Categories.RuntimeOnlyTitle))
          .Append(") section below is the only schema source for them. Absence from the listing is not proof ")
          .Append("a command does not exist — a genuinely unknown name fails with exit code 6. The reverse also ")
          .Append("holds: a project's own `[CliCommand]` methods are listed by the CLI but are not documented ")
          .Append("here, because this reference covers the package surface only.\n\n");

        sb.Append("Argument conventions: pass every argument as `--name value` (snake_case). `*` marks a ")
          .Append("required argument. Destructive commands need `--confirm true`; most mutating commands accept ")
          .Append("`--dry_run true`; async commands pair with a `*_status` poll command. A command the package ")
          .Append("compiles only on newer Unity versions says so in its entry — it does not exist on older ")
          .Append("ones, and calling it there fails with exit code 6.\n\n");
    }

    private static void Contents(StringBuilder sb, IEnumerable<string> sections, bool hasRuntimeOnly)
    {
        var links = sections.Select(s => $"[{s}](#{Categories.Anchor(s)})").ToList();
        if (hasRuntimeOnly)
            links.Add($"[{Categories.RuntimeOnlyTitle.Split(" (")[0]}](#{Categories.Anchor(Categories.RuntimeOnlyTitle)})");

        sb.Append("## Contents\n\n").Append(string.Join(" · ", links)).Append("\n\n");
    }

    private static void RuntimeOnlyPreamble(StringBuilder sb, string version, IReadOnlyList<CommandInfo> commands)
    {
        sb.Append("## ").Append(Categories.RuntimeOnlyTitle).Append("\n\n");

        sb.Append("The `[CliCommand]` attribute of every command below sets `RuntimeOnly = true`, so ")
          .Append("`unity command` neither lists them nor shows their schemas — these entries, read out of the ")
          .Append("`com.unity.pipeline` `").Append(version).Append("` package source, are the only schema source ")
          .Append("for them. They execute against the editor server despite the flag, and against Player ")
          .Append("connections (`--runtime <process>` / `--runtime-path <port file>`).");

        if (commands.All(c => c.MainThreadRequired))
            sb.Append(" All of them require the main thread.");

        sb.Append("\n\n");
    }

    private static void Entry(StringBuilder sb, CommandInfo command, Annotations annotations)
    {
        sb.Append("### ").Append(command.Name).Append('\n');

        var parts = new List<string>();
        if (command.Description.Length > 0) parts.Add(command.Description);

        if (command.MinUnityVersion is { } minimum)
            parts.Add($"**Unity {minimum}+ only** — the command is compiled under " +
                      $"`#if {SourceParser.UnitySymbolFor(minimum)}` and does not exist on older versions.");

        foreach (var condition in command.Conditions)
            parts.Add($"**Conditional** — the command is compiled only where `{condition}` holds.");

        var note = annotations.NoteFor(command.Name);
        if (note.Length > 0) parts.Add(note);

        if (!command.MainThreadRequired) parts.Add("*(works while main thread is busy)*");

        sb.Append(parts.Count > 0 ? string.Join(' ', parts) : "*(no description)*").Append('\n');

        if (command.Args.Count == 0)
        {
            sb.Append("- *(no arguments)*\n\n");
            return;
        }

        foreach (var arg in command.Args)
        {
            sb.Append("- `").Append(arg.Name).Append('`');
            if (arg.Required) sb.Append("\\*");
            sb.Append(' ').Append(arg.Type);
            if (arg.Default is { } value) sb.Append(" (default ").Append(value).Append(')');
            if (arg.Description.Length > 0) sb.Append(" — ").Append(arg.Description);
            sb.Append('\n');
        }

        sb.Append('\n');
    }
}
